task:
  matrix:
    - macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
    - container:
        image: gcc:latest
  prep_script: git submodule update --init --recursive
  compile_script: make
  install_script: sudo make install
